### ISSUE TITLE
Continuous Integration to build new dictionaries

### ISSUE THREAD

**Issue by TobiTenno** [WFCD/warframe-wikia-scrapers#4]
### Wikia Scrapers Issue
---

**Summary (short):** Add CI with Travis CI to build, test, and deploy new dictionaries.

---
**Description:** Automatically build new dictionaries from the wiki and commit them to wfcd/warframe-worldstate-data, and increment version on [API](warframe-status)'s dependencies.

---
**If issue, Reproduction:** N/A

---
**Mockups, screenshots, evidence:** N/A

---

(Check one)
- [ ] Issue
- [x] Suggestion

--- 

### Tasks

- [x] Tests (run the normal run, open file and check for known values)
- [x] Build config for Travis CI (will need to specify *nix environment and pre-install lua)
- [x] Automatically checkout latest wfcd/warframe-worldstate-data
- [x] Update wfcd/warframe-worldstate-data weapons.json
- [x] Publish wfcd/warframe-worldstate-data on npm
- [x] Update wfcd/warframe-status with new version (this will kick off a new build)

**Comment by TobiTenno** [comment]
@CMDadabo guess what? it works!

**Comment by CMDadabo** [comment]
Sweet! Well done, my man!
